# Definimos la imagen de Docker oficial de Python
image: python:3.10-slim

# Definimos las etapas del pipeline
stages:
  - lint

# Job para revisar el código
check_python_code:
  stage: lint
  before_script:
    - python -V
    - pip install flake8
  script:
    # 1. Errores críticos: si encuentra algo aquí, el pipeline falla (rojo)
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # 2. Estilo y complejidad: solo informa, no detiene el proceso (--exit-zero)
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  # Reglas de ejecución interesantes para tu flujo
  rules:
    # Corre cuando haces un push a la rama develop
    - if: $CI_COMMIT_BRANCH == "develop"
    # Corre cuando se crea un Merge Request (equivalente al Pull Request) hacia master
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
