name: Practica Pipeline 04/03/2026

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hacemos checkout del repositorio
        uses: actions/checkout@v4

      - name: Configuramos Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutamos el script
        run: python Principal.py

      - name: Instalamos pytest
        run: pip install pytest

      - name: Ejecutamos tests
        run: python -m pytest